### PR TITLE
Multi-service fixture for solving the cross-domain uploading

### PR DESCRIPTION
**Pull request by cainmagi**
## Introduction

I have added my modifications to the `dash-uploader`. The main improvement is the multi-service support, making it possible for serving app on different paths. To learn the requirements, please review issue #24. I think the modifications are enough for updating the version of this project to `v0.5.1`.

I have also updated the documentation. Please review [this link](https://github.com/cainmagi/dash-uploader/blob/multi-services/docs/dash-uploader.md#5-a-short-example-of-cross-domain-uploading) to learn how to start a minimal test. You could also search `New in version 0.5.1` for finding what new APIs I have added.

All modifications are python codes. I find that it is not necessary for modifying the React codes.

If you have any questions, please let me know. Thank you!

## Update reports

1. Add multi-service supports for `du.Upload`.
2. Add an option prevent_initial_call for `du.callback`.
3. Add `chunk_size` and `service_addr` arguments for `du.Upload`.
4. Add cross-domain supports in the module `fixture`.
5. Fix some bugs and warnings.
6. Extend the documentation.

### CODE REVIEW

**Comment by cainmagi** [comment]
@np-8 
I do not know why the package-lock.json is changed so much. I think it may be caused by my global package list of `npm`. If necessary, please remove my changes about `package.json` (except the version). Thank you!

**Comment by np-8** [comment]
Thanks for sharing @cainmagi. This is great! I will take a look at it, possibly already today evening. If this gets merged, it's probably better to bump the version to 0.6.0 as dash-uploader is using [Semantic versioning](https://semver.org/).  One thing what I'm thinking is that as there are a lot of fixes, perhaps they could be put into separate commits and even perhaps separate pull requests.

**Comment by np-8** [comment]
For the multi-service support part, did you look this: https://github.com/np-8/dash-uploader/issues/35 ? 

Really excited to merge this in, but I need to do some testing myself, and also find a way to split the changes into smaller bits. I don't have much of experience in administrating GitHub repos so I am unaware if I have the opportunity to myself do the splits. I guess one way would be to open a development branch in this repo and collaborate there. Once it looks ready to be shipped, it could be merged to the master branch.

**Comment by cainmagi** [comment]
@np-8 

Thank you for your quick reply. I am not very familiar with the Github cooperation, too. But I could roll my modifications back and split the modifications into several different commits.

For issue #35, I think it is a different topic. To my understand, my modifications only concentrate on how to deploy several different file servers. But #35 is about the synchronization between different uploading threads. This pull request would not fix the problem mentioned in #35.

**Comment by cainmagi** [comment]
@np-8 

I have rolled back to the start point from the master branch and split my modifications into 5 commits. Please help check them. Thank you!

**Comment by cainmagi** [comment]
I have uploaded a small example for testing the performance to the attachment. If you want to test the performance, you could run `app.py` in both subfolders and open the dashboard on `localhost:8060`.
Thank you!

[test_uploader.zip](https://github.com/np-8/dash-uploader/files/6392802/test_uploader.zip)

**Comment by np-8** [comment]
Thanks for the merging tip, I was just wondering how that would be done in practice. I will start checking the code you committed in an hour or two.

**Comment by cainmagi** [comment]
@np-8 

I have confirmed one thing just now:

* No matter which `service_addr` we use for `du.Upload`, the callback is always fired locally.
  * It means, when the remote service is deployed by `flask`, we need to send requests for triggering the data processing in the callback function from the local dashboard side.
  * If the remote service is a dashboard, the file could be uploaded to the remote side, but the remote callback would not be fired. Instead, the callback on the local dashboard side would be fired. I have no idea how to solve this problem now.

**Comment by np-8** [comment]
Just an update on code review: I have merged ef2a13d to master. Nice work!  I also added few things on top of it in f00c9843838deb469e117a0e0543d853d4d48eea. By the way, I use [black](https://black.readthedocs.io/en/stable/) nowadays for formatting, but seems that many of the files have not been touched a long time, and they need "blackification" (seen as `'` being converted to `"`).  

I used workflow of merging your PR to new branch `development`, and then checked out your first commit, and added something on top of it, rebased, and merged to `master`. I liked that in other ways, but perhaps it would be nice to have this PR in "open" state until it is merged to `master` (and not to a temporary branch).  Not sure if it would have been possible to just merge one commit? Or should there always be one PR per commit?  ¯\\_(ツ)_/¯

**Review by np-8 — COMMENTED** [review]
Regarding to to https://github.com/np-8/dash-uploader/pull/36/commits/302767dda66d855d1f55a7ec0df0aaf93bab1546: (Add an option `prevent_initial_call` for `du.callback`)

This is interesting and nicely written! One thing I was wondering: Could you explain why this is needed? I understand it tries to prevent some callback being called initially, but could you show an example where this would happen?

**Comment by np-8** [comment]
Regarding to https://github.com/np-8/dash-uploader/pull/36/commits/a042e499840e9ad491107a6dfc9ebc2a1ba40a8f:

Again, nicely done! Good catch this adding the `chunk_size` options.  I would merge this to master right away but I have to think a bit about the API for dash-uploader. Basically, there are two things that need configuration
- The JavaScript component needs to know where to send the packets. 
- The python code (flask server) needs to know, where to expect packets to arrive. (done currently in `du.configure_upload` automatically). The specialty here is that these need to be configured before the server it started.

Now an average user of dash-uploader probably does not care or understand much about what is happening under the hood, and he/she wants to just upload data files to server, using Dash and one Upload component. That is the easy case and it's nice that this is configured kind of automagically for the user.

Then, more advanced users, like you, would like to have multiple `du.Upload` components, and perhaps change the API.  What is suggested is fine and works (give an argument `server_address` or similar to `du.Upload`), but I just want to think a second that is that the *nicest* way for all the users to define endpoints. The potential problem in my opinion is that the opened server (Flask) route and the JS address become disconnected. Could there be some way to make this automatical so that it would be always guaranteed that for every Upload component there is opened API endpoint in Flask?

For example, could something like this be okay:

```python
import dash
import dash_html_components as html
from dash.dependencies import Output

import dash_uploader as du

app = dash.Dash(__name__)

UPLOAD_FOLDER_ROOT = r"C:\tmp\Uploads"
du.configure_upload(app, UPLOAD_FOLDER_ROOT, upload_api='my-awesome-API/upload')
du.configure_upload(app, UPLOAD_FOLDER_ROOT, upload_api='my-awesome-API/upload-second', upload_component_id='second')

# somewhere in code

# This would send to my-awesome-API/upload 
up1 = du.Upload(
    id='dash-uploader'
    # other options
)
    
# This would send to my-awesome-API/upload-second
# as API endpoint would be automatically read based on the du.Upload id
up2 = du.Upload(
    id='second'
    # other options
)
```
### Some details 

`configure_upload.py`  would save the setting based on the given `upload_component_id`, if given. The settings are then read from `du.settings` every time a `du.Upload` component is created. There is some additional magic done regarding to proxies etc. inside `du.configure_upload`, depending on the settings user has selected for `dash.Dash()` instance. That is why setting the endpoint directly at initialization of `du.Upload` would not work out of the box for some dash users. 

### What about flask?

One thing you might be considering that if this will work with Flask. I think that Flask could be supported out of the box with `du.configure_upload()`. The only thing that now does not work is this part of code in `configure_upload`:

```python
    # Needed if using a proxy
    settings.requests_pathname_prefix = app.config.get("requests_pathname_prefix", "/")
    settings.routes_pathname_prefix = app.config.get("routes_pathname_prefix", "/")

    upload_api = update_upload_api(settings.routes_pathname_prefix, upload_api)
```

But, there could be check if `app` is instance of `flask.Flask`, then these lines would not be executed (if this is desired). Also, the type of app could be saved to `du.settings`. 

How do you think about this? Is it simple enough? I consider also if it would benefit someone to be able to *manually*  set the API endpoint like you suggested, in the initialization of `du.Upload`. This would make it possible to make the component to send data to *any* webserver / service. Maybe there is a need for that, too?

**Comment by np-8** [comment]
Regarding to https://github.com/np-8/dash-uploader/pull/36/commits/89b9a21fd30911f26eba365174effb517c9ffd34 (cross-domain and flask support):

### Flask 

First about Flask. Would it make sense to you to have just one `du.configure_upload` function as I suggested in the previous comment?  I feel that adding `configure_upload_flask` just for flask does duplicate some code, and also adds some mental overhead for the users. I propose that `du.configure_upload` is modified to also accept `flask.Flask` as the first parameter.  Or do you see some additional gains from having two different functions?

### cross domain support
I'm trying to understand the motivation behind this. Did you run the receiving Flask app on another `myfirstdomain.com` and then run another Flask/Dash app for uploading at `anotherdomain.com`? I'm interested in merging this functionality, but I have to first understand what it actually does and if there are any security concerns for the users (and what kind of notes should be added to the docs). I see that for this kind of use case, one would need to use the `service_addr` that you added for `du.Upload`. 

### Concerning the callback problem 

Regarding to [this](https://github.com/np-8/dash-uploader/pull/36#issuecomment-828621214). There are basically two kinds of callbacks. 
- One would be a python callback, executing something on server side. You could use the [du.HttpRequestHandler](https://github.com/np-8/dash-uploader/blob/master/docs/dash-uploader.md#duhttprequesthandler) or a subclass of it. I'm considering for example, that there could be such subclass of `HttpRequestHandler` that calls a function every time a file upload has been finished. Currently it actually calls a logger, but this could be modified in such way that there is `callback(self, filename)` which is called each time a file upload is complete.
- Another is Dash callback. which also can trigger changes in the UI  / browser. I have not checked more thoroughly how these work under the hood, but since they are so special, they have to be defined in very special way (`du.callback` or `app.callback`).

If you run a Flask server that receives uploads, I guess that only thing that you may use is the "python side" callbacks. This is because the `app.callback`s are sent to the user in the JavaScript bundle when user loads the page. Does this help you?

I'm really impressed about your work, and thankful that you gave the PR. Also thank you for refactoring the PR to multiple commits as it made it a lot easier to read.

**Comment by cainmagi** [comment]
> Just an update on code review: I have merged [ef2a13d](https://github.com/np-8/dash-uploader/commit/ef2a13d0863f914c0590a66c8e68d5dedce27ea3) to master. ... Not sure if it would have been possible to just merge one commit? Or should there always be one PR per commit? ¯\(ツ)/¯

Thank you for replying. If you like, we could re-open this pull request. However, I suggest that this pull request is always kept for updating the `development` branch. if you want to update the master branch, I could create another pull request in the future.

-----

> Regarding to to [302767d](https://github.com/np-8/dash-uploader/commit/302767dda66d855d1f55a7ec0df0aaf93bab1546): (Add an option `prevent_initial_call` for `du.callback`) ..., but could you show an example where this would happen?

This option is designed for improving the efficiency of the callbacks. You could refer the official example [here](https://dash.plotly.com/advanced-callbacks#prevent-callback-execution-upon-initial-component-render). In this project, the callback should be always fired after the file uploaded, so I think that the initial fire is not required. It is better to make `prevent_initial_call=True` in our case.

-----

> Regarding to [a042e49](https://github.com/np-8/dash-uploader/commit/a042e499840e9ad491107a6dfc9ebc2a1ba40a8f) (Add two options `chunk_size` and `service_addr` to `du.Upload`.) ... How do you think about this? Is it simple enough? I consider also if it would benefit someone to be able to _manually_ set the API endpoint like you suggested, in the initialization of `du.Upload`. This would make it possible to make the component to send data to _any_ webserver / service. Maybe there is a need for that, too?

First, I think your idea is a better solution. The only thing I notice is that in your example,
```python
du.configure_upload(app, UPLOAD_FOLDER_ROOT, upload_api='my-awesome-API/upload-second', upload_component_id='second')
```
it may be better to provide the API like this:
```python
du.configure_upload(app, UPLOAD_FOLDER_ROOT, upload_api='my-awesome-API/upload-second', upload_component_ids=['second', 'third', ...])
```
`upload_component_ids` could be a `None`, `str` or a sequence of `str`, because we may want to provide the same API for multiple ids.

Second, I want to know that whether it is possible for configuring the apis like `upload_api=http://localhost:8061/API...`. If this configuration would not trigger errors, I think it would be OK. But I know that this value may be refined by
```python
upload_api = update_upload_api(settings.routes_pathname_prefix, upload_api)
```
I am worried that it may be not compatible with the cross-domain service if we switch the API to your suggestion.

-----

> Regarding to [89b9a21](https://github.com/np-8/dash-uploader/commit/89b9a21fd30911f26eba365174effb517c9ffd34) (cross-domain and flask support): ... I'm trying to understand the motivation behind this. Did you run the receiving Flask app on another `myfirstdomain.com` and then run another Flask/Dash app for uploading at `anotherdomain.com`? I'm interested in merging this functionality, but I have to first understand what it actually does and if there are any security concerns for the users (and what kind of notes should be added to the docs). I see that for this kind of use case, one would need to use the `service_addr` that you added for `du.Upload`.

Actually, I just copy the work from [stackoverflow](https://stackoverflow.com/a/45054690) and sucessfully try to make the codes work for our project. But I do not understand every detail of the implementation, because I am not an expert in web development. I know there is a more convenient way to do a similar job. That is using the extension [`flask-cors`](https://flask-cors.readthedocs.io). I do not use this extension because I do not want to add dependencies. If you do not mind that, you could use this extension to provide cross-domain support. It should be more compatible with other flask extensions about security or authentication.

> ... If you run a Flask server that receives uploads, I guess that only thing that you may use is the "python side" callbacks. This is because the `app.callback`s are sent to the user in the JavaScript bundle when user loads the page. Does this help you?

Personally, I prefer the following ways for the flask server:

1. Define an API on the server-side for handling the file upload complete.
2. When the local callback of the dashboard gets fired, send a request to the API mentioned in step 1.
3. Get the response of the API, and use the response to handle the return value of the local dashboard callback.

For the dash sever, I think in most cases, we do not need to upload data from the other dashboard. So maybe we could disable the implementation for this case. If we indeed need to do that, we may need hack into the dash codes and find how to trigger a callback manually.

There may be an alternative. We could modify the `du.callback` and register the callback function for another API (like what we do for flask server). If we choose this implementation, we should remind users not to use `app.callback` decorator.

**Comment by np-8** [comment]
Hi @cainmagi , 

I think I've made a mistake by merging this PR already as it kind of "closes the case on GitHub", and makes incomplete things a bit harder to track.  I think now that I should have kindly asked you to divide the commits into their own branches and give a PR per branch. This would make the whole process much more maintainable. Luckily this is the only PR which is active on this project, and this was a good lesson for me on how to manage open source project on GitHub. Could it be possible that you would still divide the PRs into smaller parts, following the [PR etiquette](https://gist.github.com/mikepea/863f63d6e37281e329f8) by mikepea? You could start one branch per each topic from the tip of the current master and cherry-pick your commit(s) there, and make a PR. I think that there are few topics that are independent on each other
- Supporting Flask. 
- Supporting cross-domain requests
- Supporting multiple du.Upload components on same page

Or maybe there is some other way to categorize these, but I think it would make things clearer, and it would be easier to accept PR's when they only contain solution to one thing.

I'm also thinking that should I try to setup some sort of automatic testing for the app as there starts to be increasing number of moving parts (using e.g. selenium). 

I really have to take more time to think how this could work technically:

> Personally, I prefer the following ways for the flask server:
>
> Define an API on the server-side for handling the file upload complete.
When the local callback of the dashboard gets fired, send a request to the API mentioned in step 1.
Get the response of the API, and use the response to handle the return value of the local dashboard callback

**Comment by cainmagi** [comment]
@np-8 
Hello! I am sorry for replying late. During each week, I could only work on the web development for 3 days.

Thank you for sharing the guides with me. During this week, I will re-implement the features in this pull request and split them into several requests. I will try to take your suggestions and improve the interfaces. Maybe I could send you some updates today.

**Pull request merged**
