### PR TITLE
Refactored By creating new components

### PR DESCRIPTION
**Pull request by Vipulsh**
Created some new components and replaced them with the code in Upload_ReactComponent.react.js.
Please feel free to suggest more refactoring if required.
Also I didn't setup the python environment , as I was only making the changes with React.

### CODE REVIEW

**Review by np-8 — COMMENTED** [review]
Thanks @Vipulsh !

**Comment by np-8** [comment]
I merged these to another branch: https://github.com/np-8/dash-uploader/tree/refactor_upload  

I also continued the refactoring by merging all of the Button components (Cancel, Start, Pause) into one Button component, and tried to tidy the code a bit. There is still room for improvement but it looks much nicer now :)

**Comment by np-8** [comment]
Actually, planning to publish these all in the next (0.5.0) release, so merged to: https://github.com/np-8/dash-uploader/tree/0.5.0

**Comment by Vipulsh** [comment]
@np-8 Thanks for reviewing and merging it. I would like to contribute more to this project. Let me know if I can connect with you or anything that you would like me to work on.

**Pull request merged**
