### PR TITLE
Handle when no iscomplete correctly in callback

### PR DESCRIPTION
**Pull request by hansharhoff**
When not iscomplete occurs in the callback the current implementation returns None which generates server side error in user console. Instead we can raise PreventUpdate() to suppress this issue.

I also added some instructions to Contributing that would help newcomers get to an installed package quicker.
Added packaging to requirements as this is needed to import dash_uploader.

### CODE REVIEW

**Comment by np-8** [comment]
Hi! Thanks for the PR! I will look at it during the coming days! :) Does this `PreventUpdate` exist in all supported `dash` versions?

**Review by np-8 — COMMENTED** [review]
Nice catch! Did not previously see that `packaging` is required to import `dash_uploader`. However, `requirements.txt` is just meant just for developers. Correct place for requirements that should be installed automatically by `pip` when installing `dash-uploader` is the `install_requires` in the `setup.py`. Could you change the location of this requirement there? 

```python
#setup.py 
    install_requires=[
        "dash>=1.1.0",
    ],
```

**Comment by np-8** [comment]
> Hi! Thanks for the PR! I will look at it during the coming days! :) Does this `PreventUpdate` exist in all supported `dash` versions?

I checked this and the `PreventUpdate` exists in `dash 1.1.0`, at least.

**Comment by np-8** [comment]
This would be ready to be merged once the `packaging` requirements is moved from `requirements.txt` to `setup.py`.

**Comment by hansharhoff** [comment]
Yes, done

**Comment by np-8** [comment]
Great! Thank you!

**Pull request merged**
